[exampleSearchPage]
#納入情報基本情報検索
GR0800_001 = "SELECT * FROM T_PURCHASE WITH(NOWAIT,UPDLOCK) WHERE ID_PURCHASE = ? AND FORMAT(UD_DATE,N'yyyy/MM/dd HH:mm:ss') = ?"
#納入情報環境認定更新
GR0800_002 = "UPDATE T_PURCHASE SET FLG_ENVIRONMENTAL_APPROVAL = ? , UD_UID = ? , UD_DATE = CONVERT(DATETIME, CONVERT(NCHAR (19), SYSDATETIME(), 120)), ENVIRONMENTAL_APPROVAL_COMMENT = NULLIF(? , ''), NO_CONTENT_CERTIFICATE_ESCAPE_CODE_ROHS = NULLIF(? , ''), MY_ANALYSIS_RESULT = NULLIF(? , ''), CERTIFIED_PERSON = NULLIF(? , ''), BIKOU1 = NULLIF(? , ''), BIKOU2 = NULLIF(? , ''), BIKOU3 = NULLIF(? , ''), NO_CONTENT_CERTIFICATE_ESCAPE_CODE_ELV = NULLIF(? , '') WHERE ID_PURCHASE = ? "
#添付ファイル実有無
GR0800_003 = "SELECT COUNT(*) FROM T_PURCHASE_FILE  WHERE  ID_PURCHASE = ?"
#製品単位除外コードと標準取得
GR0800_004 = "SELECT ESCAPE_CODE, APPLY_PRINCIPLE_CODE FROM M_ESCAPE_REGULATION WHERE ID_ESCAPE IN (SELECT DISTINCT ID_ESCAPE FROM T_PRODUCT_CHEM_ESCAPE_CODE WHERE ID_PRODUCT = ?)"
#製品調査物質群更新
GR0800_005 = "UPDATE T_PRODUCT SET ID_CHEMICAL_INV_GROUP = NULLIF(? , ''), UD_UID = ? , UD_DATE = CONVERT(DATETIME, CONVERT(NCHAR (19), SYSDATETIME(), 120)) WHERE ID_PRODUCT = ?"
#納入情報削除
#GR0800_006 = "UPDATE T_PURCHASE SET FLG_UNUSED = 1, UD_UID = ? , UD_DATE = CONVERT(DATETIME, CONVERT(NCHAR (19), SYSDATETIME(), 120)) WHERE ID_PURCHASE = ?"
GR0800_006 = "UPDATE T_PURCHASE SET FLG_ENVIRONMENTAL_APPROVAL = 0, UD_UID = ? , UD_DATE = CONVERT(DATETIME, CONVERT(NCHAR (19), SYSDATETIME(), 120)), ENVIRONMENTAL_APPROVAL_COMMENT = '', NO_CONTENT_CERTIFICATE_ESCAPE_CODE_ROHS = '', MY_ANALYSIS_RESULT = 0, CERTIFIED_PERSON = '', BIKOU1 = '', BIKOU2 = '', BIKOU3 = '', NO_CONTENT_CERTIFICATE_ESCAPE_CODE_ELV = '' WHERE ID_PURCHASE = ? "
#製品情報基本情報検索
GR0800_007 = "SELECT * FROM T_PRODUCT WITH(NOWAIT,UPDLOCK) WHERE ID_PRODUCT = ? AND FORMAT(UD_DATE,N'yyyy/MM/dd HH:mm:ss') = ?"
#GR0350の表示と一致するため、TH_PRODUCTの調査物質群更新
GR0800_008 = "UPDATE TH_PRODUCT SET ID_CHEMICAL_INV_GROUP = NULLIF(? , ''), UD_UID = ? , UD_DATE = CONVERT(DATETIME, CONVERT(NCHAR (19), SYSDATETIME(), 120)) WHERE TH_PRODUCT.ID_PRODUCT = (SELECT TH.ID_PRODUCT FROM T_PRODUCT TP INNER JOIN T_PRODUCT_COMPANY TPC ON TPC.ID_PRODUCT = TP.ID_PRODUCT AND TPC.DIV_PRODUCT_COMPANY = 1 INNER JOIN TH_PRODUCT TH ON TH.CD_PRODUCT = TP.CD_PRODUCT INNER JOIN TH_PRODUCT_COMPANY THPC ON THPC.ID_PRODUCT = TH.ID_PRODUCT AND THPC.DIV_PRODUCT_COMPANY = 1 AND TPC.CD_COMPANY = THPC.CD_COMPANY WHERE TP.ID_PRODUCT = ? )"
#お客様側入力した除外コード(RoHS)がDBに存在するかどうかをチェックする
GR0800_009 = "SELECT DISTINCT ESCAPE_CODE FROM M_ESCAPE_REGULATION WHERE APPLY_END_DATE > SYSDATETIME() AND APPLY_PRINCIPLE_CODE IN ('R', 'R,E') AND ESCAPE_CODE = ?"
#お客様側入力した除外コード(ELV)がDBに存在するかどうかをチェックする
GR0800_010 = "SELECT DISTINCT ESCAPE_CODE FROM M_ESCAPE_REGULATION WHERE APPLY_END_DATE > SYSDATETIME() AND APPLY_PRINCIPLE_CODE IN ('E', 'R,E') AND ESCAPE_CODE = ?"